config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  resources :buildings

  resources :buildings do 
    resources :apartments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "buildings#index"
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartments, dependent: :destroy
    accepts_nested_attributes_for :apartments
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :find_building
  before_action :set_apartment, only: %i[ show edit update destroy ]

  # GET /apartments or /apartments.json
  def index
    @apartments = @building.apartments
  end

  # GET /apartments/1 or /apartments/1.json
  def show
    @apartment = Apartment.find(params[:id])
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
    @apartment = Apartment.find(params[:id])
  end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.building = @building

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to building_apartment_path(@building, @apartment), notice: "Apartment was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    @apartment = Apartment.find params[:id]
    respond_to do | format|
      if @apartment.update(apartment_params .merge(building: @building))# Se añade el building que se obtuvo en la llamada a find_building
        format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'Apartment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
   

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    @apartment = Apartment.find params[:id]
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to building_apartments_url, notice: 'Apartment was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:number)
    end

    def find_building
      @building = Building.find(params[:building_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
    @building.apartments.build
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:name, apartments_attributes:[:id, :number, :_destroy])
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper

    def edificios_for_select
        Building.all.collect{|p| [p.name, p.id]}
    end

end

app/views/apartments/_apartment.html.erb
<div id="<%= dom_id apartment %>">
  <p>
    <strong>Number:</strong>
    <%= apartment.number %>
  </p>

  <p>
    <strong>Building:</strong>
    <%= apartment.building_id %>
  </p>

</div>

app/views/apartments/_form.html.erb
<%= form_with(model: [@building, apartment], local: true) do |form| %>

  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>
      <ul>
        <% apartment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment </h1>
<%= render 'form', apartment: @apartment %>
<%= link_to 'Show', building_apartment_path(@building, @apartment) %> |
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Apartments</h1>
<table>
  <thead>
    <tr>
    <th>Number</th>
    <th>Building</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
 <% @apartments.each do |apartment| %>
  <tr>
    <td><%= apartment.number %></td>
    <td><%= apartment.building.name %></td>
    <td><%= link_to 'Show', building_apartment_path(@building, apartment) %></td>
    <td><%= link_to 'Edit', edit_building_apartment_path(@building, apartment) %></td>
    <td><%= button_to 'Destroy', building_apartment_path(@building, apartment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
 <% end %>
</tbody>
</table>
<br>
<%= link_to 'New Apartment', new_building_apartment_path(@building) %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>
<%= render 'form', apartment: @apartment %>
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @apartment.number %>
</p>
<p>
  <strong>Building:</strong>
  <%= @apartment.building.name %>
</p>
<%= link_to 'Edit', edit_building_apartment_path(@building, @apartment) %> |
<%= link_to 'Back', building_apartments_path(@building) %>

app/views/buildings/_building.html.erb
<div id="<%= dom_id building %>">
  <p>
    <strong>Name:</strong>
    <%= building.name %>
  </p>

</div>

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Building fields </p>
    <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>
    <p>Apartment fields </p>
    <%= form.fields_for :apartments do |apartment_form | %>
    <%= apartment_form .label :number %>
    <%= apartment_form .text_field :number %>
    <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Show this building", @building %> |
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buildings</h1>

<div id="buildings">
  <% @buildings.each do |building| %>
    <%= render building %>
    <p>
      <%= link_to "Show this building", building %>
    </p>
  <% end %>
</div>

<%= link_to "New building", new_building_path %>
<br>

<%= link_to "Apartments", apartments_path %>


<br><br><br>

<%

Building.includes(:apartments).each do |building|
  building.apartments.each do |apartment|
    puts apartment.number
  end
end


%>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @building %>

<div>
  <%= link_to "Edit this building", edit_building_path(@building) %> |
  <%= link_to "Back to buildings", buildings_path %>

  <%= button_to "Destroy this building", @building, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Relacionscaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>